### PR TITLE
SLING-11344 Compatibility with installer core3.9

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by kwin** [comment]
@cziegeler @rombert I am gonna merge and start a release for 1.0.4 if I don't hear any objections till end of this week.

**Comment by rombert** [comment]
@kwin  - I don't have any objections. At the same time, the diff includes several old commits, it would be easier to review if it would only include your commit.

**Comment by kwin** [comment]
> At the same time, the diff includes several old commits, it would be easier to review if it would only include your commit.

It actually includes all commits until the most recent one from develop (i.e. feature-parity with version 1.1.0+) as it turns out everything can be backported easily without issues. I am gonna clarify in the JIRA ticket.

**Comment by rombert** [comment]
Sorry, missed the target branch.

**Review by rombert — APPROVED** [review]

**Pull request merged**
